### ISSUE TITLE
Texts in the Options Menu doesn't display correctly

### ISSUE THREAD

**Issue by rlezuez** [groovesquid/groovesquid#10]
![bug-groovesquid](https://cloud.githubusercontent.com/assets/6315895/3422843/42b946d6-ff6b-11e3-8c8b-f3ddd52f34f2.PNG)
As you can see, the help texts for the options doesn't display correctly, they appear with bugged characters. Note that i'm using Spanish language, but i changed it to English and hit the "Save and Close" button, and then go to the options menu again and nothing happened, it stills displaying the texts bugged.

**Comment by gbhrdt** [comment]
Should be fixed now
