### ISSUE TITLE
Groovesquid + MusicBrainz = Mind Blown

### ISSUE THREAD

**Issue by svallory** [groovesquid/groovesquid#15]
Hey guys, first of all, THANKS!!!! I love groovesquid. It's a lifesaver! 

I took upon myself to finally organize my music collection. Most of it came from cds I imported decades ago so I actually had pretty decent metadata which makes the job easier, especially using [MusicBrainz-Picard](http://musicbrainz.org/doc/MusicBrainz_Picard). The problem with my lib is that, since I've moved the files around quite a bit, from one computer to another, etc, some files got lost and now I have loads of almost complete CD's, missing 1 to 3 songs. 

That's where GrooveSquid comes in. It's much easier to download the missing songs then to re-import them. So I've been switching from Picard to groovesquid everytime I see a missing song, which is a lot of legwork, but it's actually not so bad (at least compared to what it would be like without groovesquid).

Well, my idea for you guys is to integrate both apps. A [Picard plugin](http://musicbrainz.org/doc/MusicBrainz_Picard/Plugins/API) could call grooviesquid requesting a song. Before delivering it, groovesquid should check if the song downloaded from GS really matches the song requested through [Picard's web service](http://musicbrainz.org/doc/Developer_Resources) or, even better, compare the requested song and the downloaded one using [AcoustID](https://acoustid.org). That would make it super easy to fix libs and I think this combo would beat any other option out there.

I'm also a developer and it sounds like a lot of work to me, so I won't be bothering you to implement this, specially since I don't have time to help coding it. But I wanted to tell my idea and see what happens :)

Cheers!
And, again, THANKS!

**Comment by svallory** [comment]
Sorry, but I'm involved with too many OS projects already. I simply don't hhave the time :/

**Comment by gbhrdt** [comment]
No problem ;). I'll look into it, maybe I'll implement it soon, when I have the time to do it.

**Comment by gbhrdt** [comment]
Musicbrainz support has been added in ef6c8f40a5481c8443345af1888a7f2d17569902
