### ISSUE TITLE
"Download" doesnt do anything :(

### ISSUE THREAD

**Issue by darwin1982** [groovesquid/groovesquid#26]
Have tired, single files, full playlists.. changed directories.. save options.. tried everything, but anytime I click download, it does nothing :( almost like the button has been disabled.

**Comment by gbhrdt** [comment]
Please try starting Groovesquid.jar via your console (cmd on Windows):

java -jar Groovesquid.jar

and see if there is any exception in the output of your console while pressing the download button

**Comment by barronlroth** [comment]
Same issue here :sob:  Worked the first few times, but now the download button is basically disabled. Play button works.

**Comment by gbhrdt** [comment]
You probably need to reset your settings, because you were using the wrong filename scheme!
