### ISSUE TITLE
Retry Failed downloads

### ISSUE THREAD

**Issue by Jeremyqwerty** [groovesquid/groovesquid#30]
I love groovesquid for Mac it works great!
but when i set the download folder to
 (itunes media/automatically add to itunes ) "folder" i get an error on each song, so i click "retry failed downloads" and bellow it duplicates that song in the list thousands of times with the 
 progess displaying: cancelled and sadly freezes - need to force quit to continue 

os x Yosemite 10.10.2

**Comment by gbhrdt** [comment]
Yo, are you using the newest version available? Do you know how to show the console output?
