### ISSUE TITLE
JRELoadError when opening Groovesquid.

### ISSUE THREAD

**Issue by Coen83** [groovesquid/groovesquid#32]
Always used an older version of Groovesquid but now it says I have to download an older version of Java. Don't like to do that so I thought, let's download the latest version. After opening I got this error message:

"JRELoadError when opening Groovesquid."

**Comment by Coen83** [comment]
Just found the answer on the Groovesquid Facebook page. Just updated my Java to the latest version and it works!

**Comment by gbhrdt** [comment]
Alright!
