### ISSUE TITLE
Exe running, moving, or deleting takes minutes on Windows 7 64 bit

### ISSUE THREAD

**Issue by evesira** [groovesquid/groovesquid#35]
For some odd reason, any access to the Groovesquid exe (running, moving, deleting, properties, etc.) take about a minutes to complete on Windows 7 64 bit. This problem only happens with the Groovesquid exe, and has never happened with any other exe. (I have RAID'ed SSDs, so I don't think access time is a valid problem). Has anyone else experienced this?

**Comment by gbhrdt** [comment]
This sounds like a very weird issue to me. I'll try to reproduce it. Did you try another system?

**Comment by gbhrdt** [comment]
I'm sorry, but it works like a charm for me. Please tell me when you still have the issue and I'll reopen the issue.

**Comment by evesira** [comment]
It's okay, I couldn't replicate the issue on my work computer, Windows 7 32
bit. It probably has something to do with the Java runtime on my home
computer...

On Tue, Apr 21, 2015 at 9:49 AM, Marius Gebhardt <notifications@github.com>
wrote:

> I'm sorry, but it works like a charm for me. Please tell me when you still
> have the issue and I'll reopen the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groovesquid/groovesquid/issues/35#issuecomment-94798669>
> .
>



-- 
*Vince Rubinetti*
