### ISSUE TITLE
Mac: Version 0.8.2 JRELoadError

### ISSUE THREAD

**Issue by muhammad-saleh** [groovesquid/groovesquid#36]
I'm running Yosemite 10.10.3
GrooveSquid version 0.7.x was working fine, But today I got a message that there's a new version so I downloaded the new version and when I try to open it I get just a simple alert box with JRELoadError and the app closes instantly
I tried to install the .jar version and I got this:
"
The Java JAR file "Groovesquid.jar" could not be launched
Check the Console for possible error messages.
 "

Any idea why's that happening ?

**Comment by gbhrdt** [comment]
You need to install Java 7. I'll be implementing a better error message for future versions!
