### ISSUE TITLE
Grooveshark is down, forever.

### ISSUE THREAD

**Issue by tiferrei** [groovesquid/groovesquid#38]
I'm afraid grooveshark is down forever due to copyright infringements and legal battles.

**Comment by gbhrdt** [comment]
https://www.facebook.com/groovesquid/posts/792822704148351

**Comment by UserContributer** [comment]
## Grooveshark is really gone for good! :(

Please take down your app because grooveshark is no longer in service do to a copyright right settlement even it's website http://grooveshark.com/ says so!

Screenshot:
![grooveshark_really_is_shut_down](https://cloud.githubusercontent.com/assets/11468845/7462608/da8d4b70-f280-11e4-9815-68c9bf7b2b75.PNG)

**Comment by UserContributer** [comment]
Now I realize that grooveshark not only shutdown, but they also no longer own the website so it's really gone for good and it would be better if these grooveshark downloading apps be taken down to prevent angry users and ruining your reputation as a developer!

**Comment by gbhrdt** [comment]
Hi @UserContributer 
I understand your angriness, but unforuntately coding Groovesquid took lots of time for me, therefore it's a personal request to keep Groovesquid alive. As already stated in the Facebook post, "I already had plans to add other streaming services as sources for Groovesquid (e.g. Spotify, Soundcloud, ..), which would mean that we would now longer depend on a single service".
I'll put a message on Groovesquid's website and take down the downloads as the software doesn't work.

**Comment by eridal** [comment]
GrooveShark is not dead!

http://grooveshark.io

**Comment by gbhrdt** [comment]
We won't support any fake sites like Grooveshark.io. However, NeteaseMusic (China's Spotify) & SoundCloud are now supported!
