### ISSUE TITLE
Artists search not returning results

### ISSUE THREAD

**Issue by zaqk** [groovesquid/groovesquid#47]
I am able to search songs and albums correctly but I am unable to find results for any artists. If this is happening to anyone else I'll look into fixing it.

![groovesquidsearchissue](https://cloud.githubusercontent.com/assets/10659278/7792633/2d0a2670-027b-11e5-880f-16ff2dee5604.PNG)

![groovesquidsearchissue2](https://cloud.githubusercontent.com/assets/10659278/7792671/c1bf016e-027b-11e5-9232-6c9730e90799.PNG)

**Comment by gbhrdt** [comment]
Hi @zaqk, this feature has not been yet imlpemented fully by me. You are free to create a pull request :). Otherwise, I can fix that, too.
