### ISSUE TITLE
Downloaded Songs have incorrect Context Menu

### ISSUE THREAD

**Issue by sjonez** [groovesquid/groovesquid#48]
On the downloads tab, if you right click a downloaded song you get the same context menu as the search tab ("Download" and "Play"), download obviously doesn't make sense but neither of the options do anything when you click them either.

In the previous version, there was the option to open the file and open the folder, so it'd be great to see those return too!

**Comment by gbhrdt** [comment]
Is already fixed and will be included in the next version, thanks!
