### ISSUE TITLE
"Groovesquid Quit Unexpectedly"

### ISSUE THREAD

**Issue by HaleyMH** [groovesquid/groovesquid#51]
I'm currently running on Mac OS X 10.6.8 and every time I try to open groovesquid it says it has quit unexpectedly and I've tried to reopen it repeatedly. I've been using groovesquid for over a year. I haven't had an issue until now.

**Comment by bowmasters** [comment]
You might need to update your java version. You'll have to get it directly from the vendor: http://www.java.com/en/download/

**Comment by gbhrdt** [comment]
@bowmasters 
Normally, you should be able to download the latest Java Runtime Environment vor OS X from http://www.java.com/en/download/ :) What you're linking to is the Java Development Kit.

**Comment by bowmasters** [comment]
Unfortunately, the latest jre is not available to download for OS X 10.6.8

**Comment by gbhrdt** [comment]
Hi @bowmasters I'm sorry, you're totally right. As already said, v0.9.2 of Groovesquid should be working, as Java 1.7 is no more a requirement.
