### ISSUE TITLE
Album List, Sort by Number of Songs in Album

### ISSUE THREAD

**Issue by Seaspider1** [groovesquid/groovesquid#57]
![screen shot 2015-07-02 at 12 21 14 pm](https://cloud.githubusercontent.com/assets/11847081/8483227/d6231008-20b4-11e5-884e-ca83503a9c80.png)

The list for number of songs in each album of an artist recognizes the order of 2, 21, 29, 3, 34, 4 rather than 2, 3, 4, 21, 29, 34.

Version 0.9.3
Mac OS X 10.10.1

**Comment by gbhrdt** [comment]
The fix will be included in the next version ;).
