### ISSUE TITLE
OS X download error

### ISSUE THREAD

**Issue by Seaspider1** [groovesquid/groovesquid#60]
I'm having trouble downloading the 9.4.0 update for OS X.  The download will start but fail within  3.2 MBs of starting.  I don't believe it's a issue on my end, as I've tried multiple browsers and my network multiple times.  I could be wrong, but I thought I'd let you know.

OS X 10.10.1

I have been able to successfully download the jar file, just not the dmg.

**Comment by gbhrdt** [comment]
It works for me o.O
https://github.com/groovesquid/groovesquid/releases/download/v0.9.4/Groovesquid.dmg
