### ISSUE TITLE
Bad ID in SoundCloud

### ISSUE THREAD

**Issue by Resousse** [groovesquid/groovesquid#66]
Hi

Not sure it will happen for every tracks but on one I just tried, the bad ID was used (according to the ones provided in the track response).

The result of the first request was : 
[{"download_url":null,"key_signature":"","user_favorite":false,"likes_count":1,"release":"","attachments_uri":"api.soundcloud.com/tracks/51264555/attachments","waveform_url":"w1.sndcdn.com/zxg0S2Nf2Mpn_m.png","purchase_url":null,"video_url":null,"streamable":true,"artwork_url":null,"comment_count":0,"commentable":true,"description":"","download_count":0,"downloadable":false,"embeddable_by":"all","favoritings_count":1,"genre":"","isrc":"","label_id":null,"label_name":"","license":"all-rights-reserved","original_content_size":1812941,"original_format":"mp3","playback_count":394,"purchase_title":null,"release_day":null,"release_month":null,"release_year":null,"reposts_count":0,"state":"finished","tag_list":"","track_type":"","user":{"avatar_url":"i1.sndcdn.com/avatars-000083317445-3q59ez-large.jpg",**"id":1645177**,"kind":"user","permalink_url":"http://soundcloud.com/jean-jean-1","uri":"https://api.soundcloud.com/users/1645177","username":"jean jean","permalink":"jean-jean-1","last_modified":"2015/04/16 12:26:07 +0000"},"bpm":null,"user_playback_count":null,**"id":51264555**,"kind":"track","created_at":"2012/06/29 15:58:08 +0000","last_modified":"2012/06/29 15:58:24 +0000","permalink":"le-roi-des-papas-com-05","permalink_url":"https://soundcloud.com/jean-jean-1/le-roi-des-papas-com-05","title":"Le Roi des Papas.com 05 CETENKIKI","duration":75443,"sharing":"public","stream_url":"https://api.soundcloud.com/tracks/51264555/stream","uri":"https://api.soundcloud.com/tracks/51264555","user_id":1645177,"policy":"ALLOW","monetization_model":"NOT_APPLICABLE"}]

As you can see two ID are returned, and in this case the second one (the first one is actually the user ID and not the track ID) was not used, but was the good one

**Comment by gbhrdt** [comment]
Hi, this should not happen. How did you know the wrong ID was used?
In https://github.com/groovesquid/groovesquid/blob/master/src/main/java/com/groovesquid/service/hoster/Soundcloud.java it clearly says `songs.get(0).asObject().get("id")` which should take the right ID

**Comment by Resousse** [comment]
Actually, I downloaded the song and it was not the expected one.

I was wrong, the downloaded song is not either the second ID, might be the good ID on another source (original one was soundcloud), I will try to download the source code later today in order to find what is wrong.
You can try with "cetenkiki" https://soundcloud.com/jean-jean-1/le-roi-des-papas-com-05

**Comment by gbhrdt** [comment]
There are some songs (about 1%, I guess) on Soundcloud, that have to be downloaded with another ID, you're right. You can look at JDownloader's source: https://github.com/svn2github/jdownloader2/blob/master/src/jd/plugins/hoster/SoundcloudCom.java

**Comment by Resousse** [comment]
Finally found the issue, musicbrainz is returning the real artist, the SoundCloud hoster class is searching the song with the "title + the artist", the issue is this song (pretty rare I admit) is only referenced with the title (the artist is not mentionned :) )

It was a non-bug, sorry :)

**Comment by gbhrdt** [comment]
Yeah, this is kind of a problem. If you have anything to improve to this search query generation, please tell me!
